### ISSUE TITLE
Externalize plugins from systems

### ISSUE THREAD

**Issue by risq** [superpowers/superpowers#15]
Hi ! First, congrats for the open-sourcing ! That's an awesome project :)

I have a question regarding plugins and package management :
Currently the plugins used by a system are stored (and versioned) in the `plugins/` directory under different namespaces. Some plugins are used in different systems (`common`) and are fetched using git submodules.

As every plugin has a `package.json` in superpowers, why not just using npm to resolve plugins dependencies ? (and, potentially, to use systems as superpowers dependencies ?)

This may bring many benefits: maintainability, installing and updating plugins from cli/ui, nested dependencies...

I made [some quick tests](https://github.com/risq/superpowers/commit/8f41df58d71542630f04c3b3c2a3c151e108628d) if you are interested. This is just a proof of concept (a quick hack on the system loader).

If you want to test it, just clone the repo (`git@github.com:risq/superpowers.git`), checkout on `externalized-plugins`, clone the official `superpowers-game` into `./systems`. 

Then manually delete `plugins/default/font` and build superpowers. Add the external font plugin (https://github.com/risq/superpowers-game-sparklinlabs-font-plugin) dependency with `npm i risq/superpowers-game-sparklinlabs-font-plugin --save`. Run the server, you should see the fonts plugin properly loaded.

Tell me what you think about this, and thanks for your great work !

**Comment by elisee** [comment]
Hi! Thank you so much for the kind words and for diving into the project like that :D.

Just wanted to say that we're thrilled you went and made a proposal so quickly about the insides of Superpowers with an actual proof of concept! @bilou84 and I have started discussing it and we'll come back soon with thoughts.

Cheers!

**Comment by risq** [comment]
No problem. Keep me in touch :)

**Comment by elisee** [comment]
OK so here are some thoughts after @bilou84 and I talked some more. First, some context:

The goal for Superpowers 1.0 is to have the main app folder be just Electron + the redesigned launcher. We'd move `systems/` into the user data folder (so, `%APPDATA%/Superpowers/systems` on Windows for instance), as well as the server itself, so that they could all be updated independently.

The server will gain command line arguments that might look like this:

    node server update --all # Update everything
    node server update --core # Update the client/server
    node server install game # Install the Superpowers Game system
    node server install game:florentPoujol/ftext # Install @florentpoujol's fText plugin for Sup Game

(The exact syntax doesn't matter too much, but you get the idea). And the launcher would use a similar API exposed by the server to do this with bells and whistles in the UI.

The various systems and plugins would be found in a registry of some kind. We could conceivably use npm as our registry (that would require bundling npm as part of the launcher or server, since we can't assume it is installed).

But npm has this whole dependency tree thing that might be slower and more fragile that what we want. What if a system or plugin uses a semver range for a dependency (like `^1.2.0`) and that dependency is updated in a non-semver compliant way, or breaks for any other number of reasons? Yes, it's not supposed to happen, but it happens from time to time, and that would make the experience pretty poor for end-users who just want their stuff to work, every time all the time.

It seems more robust to simply download systems and plugins as ZIP files whose content have been tested and set in stone by their author. So, what would it take to build our own registry? Well, maybe not too much!

For starters, we could simply have a `superpowers-registry` repository (or have it as part of the `superpowers` repo) on GitHub that contains a `registry.json` file with a list of systems and their plugins. When someone wants to publish a new system or plugin, they simply send a pull request to edit that file.

The registry client (through the server command line or the launcher app) would fetch this file, that would look a bit like this:

```json
{
  "game": {
    "repository": "https://github.com/superpowers/superpowers-game",
    "plugins": {
      "cannonjs": "https://github.com/superpowers/superpowers-game-cannonjs-plugin",
      ...
    }
  },
  "web": {
    "repository": "https://github.com/superpowers/superpowers-web",
    "plugins": { ... }
  }
}
```

And we would use GitHub's REST API to fetch the latest release in the repositories (example: http://api.github.com/repos/superpowers/superpowers/releases/latest), download the appropriate ZIP and unzip it where it belongs. We would entirely rely on GitHub for infrastructure (which is totally fine for the foreseeable future, or even forever).

I think that would provide a nice experience for both system/plugin devs and game devs, with [a cool UI](https://trello-attachments.s3.amazonaws.com/5671b39bff14beb29683c598/1939x1300/84ea175ad078e990b525d48c1b78d9e8/part2.png) for managing your server from the launcher and a simple commandline interface for headless servers.

What do you think? Did we miss something about npm that would make it a better choice?

**Comment by risq** [comment]
OK, I get the idea. I think this may actually be more beginner-friendly, which is obviously a good thing for superpowers.

However this may bring some disadvantages for more advanced developers, potential plugin developers and for anyone coming from the js/nodejs ecosystem (like me), which have to be considered : 
- Not specifying a release version and using the `latest` tag to resolve a plugin dependency would be a major integrity issue to me. Even if it doesn't update automatically, how can I be sure to use the same version of a plugin as someone else working on the same project ?
- I agree with the fact that a misuse of semver versioning from plugins developers can be an issue for the users. However, not using semver ranges for dependencies (by default) can be a way to limit this kind of problems, and to guarantee package integrity. Working on a smart dependencies manager/package updater UI on top of npm may bring more benefits that working on a custom dependencies system (I think :) ).
- Pull request based registry updating is totally manageable now, but may be increasingly complicated as superpowers will grow (and I'm sure it will grow fast !).
- Have you thought about a way to handle nested dependencies with this solution ?

In addition, I'd just like to add two benefits which may also be considered : [package integrity](http://blog.npmjs.org/post/77758351673/no-more-npm-publish-f) and [npm test/install/publish scripts](https://docs.npmjs.com/misc/scripts), which can be helpful to ensure that tests and build have successfully been run before publishing any plugin to npm.

This is just my opinion, as a javascript developer. I know this may need some time to make it work easily for everybody (users & plugins developers), so this may not be something worth it now and for the v1.0. In any case, [switching from a custom registry to npm will always be possible](https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html) in the future, even if it would involve some work from the plugins developers :)

**Comment by elisee** [comment]
> Not specifying a release version and using the latest tag to resolve a plugin dependency would be a major integrity issue to me. Even if it doesn't update automatically, how can I be sure to use the same version of a plugin as someone else working on the same project ?

People working on a project together would be connecting to the same server. The server is the one installing the plugins, not the clients. Although we might need to store the versions of all the system and plugins used in a file as part of the project so that the server owner (or someone else redeploying the project elsewhere) can be notified of the version mismatches and a log of version changes with release notes / upgrade instructions for each plugin. cc @bilou84

> Working on a smart dependencies manager/package updater UI on top of npm may bring more benefits that working on a custom dependencies system (I think :) ).
> ...
> Have you thought about a way to handle nested dependencies with this solution ?

I think we won't be having much of a dependency system at all, there are only two levels of packages: systems and plugins. Both are basically distributed as opaque ZIP files.

> Pull request based registry updating is totally manageable now, but may be increasingly complicated as superpowers will grow (and I'm sure it will grow fast !).

True! Let's cross that bridge when we get to it :D

> In addition, I'd just like to add two benefits which may also be considered : package integrity and npm test/install/publish scripts, which can be helpful to ensure that tests and build have successfully been run before publishing any plugin to npm.

Knowing for a fact that the package won't change is good stuff, and not something we can do with GitHub indeed...

Good-behaved plugin developers will use continuous integration and generate builds and/or tests for each commit, just as they would when publishing to npm. Similarly, those who don't care about it won't care no matter whether their publings are published npm or GitHub, will they?

> This is just my opinion, as a javascript developer. I know this may need some time to make it work easily for everybody (users & plugins developers), so this may not be something worth it now and for the v1.0. In any case, switching from a custom registry to npm will always be possible in the future, even if it would involve some work from the plugins developers :)

Yeah, basically right now @bilou84 and I believe we don't need a package manager with complex dependencies and all the bells and whistles of `npm`, but it might turn out we're wrong and if that happens, we'll definitely reconsider.

If you're OK with that resolution for now and have nothing to add, feel free to close the issue :)

**Comment by risq** [comment]
OK, no problem !
