### ISSUE TITLE
OSX: Empty atom.icns leads to crash when publishing game

### ISSUE THREAD

**Issue by aaronsdevera** [superpowers/superpowers#38]
Unable to publish games using the one-click Publish project button located in the top-left corner.
Application exit, then system alert raised: "Superpowers quit unexpectedly." 
OSX 10.11.2

**Comment by elisee** [comment]
Well, this is a weird one. The atom.icns icon for Superpowers in v0.18.1 is a zero-byte file, and that's why it crashes! Not sure why electron-packager failed to package it when it was properly copied in v0.18.0 and previous releases.

Anyway, I'll make sure it's fixed when I package 0.19.0 today or tomorrow. In the meantime, as a workaround, you can grab Contents/Resources/atom.icns from v0.18.0 and replace the one in your v0.18.1 package...
