### ISSUE TITLE
Use ES5 strict mode?

### ISSUE THREAD

**Issue by elisee** [superpowers/superpowers#70]
Should we be using [ES5 strict mode](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Strict_mode) for performance and/or better runtime error detection?

If so, do we need to put the `"use strict";` marker in each file? Only the entry files for Node.js? What about browserified modules? Is it enough to put it at the top of the browserify bundles, or do we need one inside each module like [strictify](https://github.com/jsdf/strictify) does?

**Comment by elisee** [comment]
@fasterthanlime do you have any insight into these questions? Did some research but I haven't found a very good source about it.

**Comment by fasterthanlime** [comment]
@elisee The reason I've been using `"use strict"` in [itch](https://github.com/itchio/itch/) is because it unlocks ES6 features in Chrome & node.js that are otherwise unavailable, such as `let` and others I don't quite remember.

If you bundle like you seem to be doing, you can't just slap `"use strict"` at the start of the bundle, because it'll apply to your bundled dependencies as well, which will often be troublesome. Instead, you need to have it inside each module, the safest way is via an [IIFE](http://benalman.com/news/2010/11/immediately-invoked-function-expression/):

```javascript
(function () {
  "use strict" // only applies to this function body
  // ... insert module contents here ...
})();
```

If/when you do enable it, make sure any `"use strict"` is inside wrappers like that, and not at the top-level, or you'll have nasty surprises:

  * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Invoking_strict_mode
  * https://github.com/systemjs/builder/issues/387

**Comment by elisee** [comment]
@fasterthanlime thanks for the info! Didn't think of `"use strict"` possibly breaking dependencies in a bundle, that's good to know.

Well, since it doesn't seem to be a huge win in any department for now, let's forget about it and revisit later if someone comes with a convincing reason to do so!

**Comment by elisee** [comment]
Well, TypeScript 1.8 will emit `"use strict";` by default so that's pretty cool :D https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#modules-are-now-emitted-with-a-use-strict-prologue

**Comment by fasterthanlime** [comment]
@elisee I forgot you were using TypeScript! You probably get a lot of the checks that strict mode does for vanilla JS anyway.
